home: dev_docs/HOME.md
contents:
  - title: 'Inspector'
    items:
      - title: Extend Inspector
        markdown: src/ui/public/visualize/loader/loader_examples.md
        id: extend-inspector
      - title: Use Inspector
        markdown: src/ui/public/visualize/loader/loader_usage.md
        id: use-inspector
      - title: Inspector JS API
        id: inspector-api
        jsdoc: src/ui/public/visualize/loader/**/*
      - title: Inspector API
        stage: beta
        id: inspector-server-api
        swagger: src/ui/public/visualize/loader/inspector_api.spec
